### Registrar novo contato
POST http://localhost:8000/contato HTTP/1.1
content-type: application/json

{
    "nome": "Jan Cloude da Silva Andrade",
    "telefone": "987120712",
    "endereco": "rua caraiva, cond. solar de maiorca, ap 504, bl 2",
    "email": "andrade@gmail.com",
    "cpf": "85795567590"
}