exports.Tamanhos = {
  PEQUENO: 'PP',
  PEQUENO: 'P',
  MEDIO: 'M',
  GRANDE: 'G',
  MAIOR: 'GG'
}

exports.Status = {
  SOLICITADO: 'SOLICITADO',
  CONFIRMADO: 'CONFIRMADO',
  PAGO: 'PAGO',
  FINALIZADO: 'FINALIZADO',
  CANCELADO: 'CANCELADO'
}